#!/bin/bash
#ssh attack to 10.0.10.10 in HoneyNet 1


#HoneyNet1###
##SSH SERVER 10.0.10.10


echo "which IP to target for ssh attack?"

read target

echo "What is the username?"

read username

echo "What is the password?"

read -s password


ssh "$username@$target"

#ssh-keygen -f "/root/.ssh/known_hosts" -R "10.0.10.10"
